print("Let's do a couple of arithmatic operations on 2 integers")
var1 = int(input("Enter first number"))
var2 = int(input("Enter second number"))
var3 = int(input("Enter third number"))
print('Add: ',var1+var2+var3)
print('Difference: ',var1-var2-var3)
print('Multiply: ',var1*var2*var3)
print('Power: ',(var1**var2)**var3)
print('Divide: ',(var1/var2)/var3)
