print("Let's do a couple of arithmatic operations on 2 integers")
var1 = int(input("Enter first number"))
var2 = int(input("Enter second number"))
print('Add: ',var1+var2)
print('Difference: ',var1-var2)
print('Multiply: ',var1*var2)
print('Power: ',var1**var2)
print('Divide: ',var1/var2)
